// CATEGORY RESOURCES - Categories to filter
export const categoriesToFilter = [
  "Building material",
  "Tool",
  "Jewelry",
  "Household goods",
  "Drink",
  "Other",
  "Electronics",
  "Lubricant",
  "Food",
  "Info",
  "Battery",
  "Medical supplies",
  "Locking container",
  "Fuel",
  "Common container",
  "Drug",
  "Medical item",
];